language: r
sudo: required
cache: packages
r_github_packages:
    - r-lib/covr
    - r-lib/fs
after_success:
    - Rscript -e 'covr::codecov()'
warnings_are_errors: false
os:
  - linux
apt_packages:
 - r-cran-rjava
