language: r
sudo: true
cache: packages
r_github_packages:
    - r-lib/covr
    - r-lib/fs
after_success:
    - Rscript -e 'covr::codecov()'
warnings_are_errors: false
dist: trusty
os:
  - linux
  - osx